# Generated by Django 4.2 on 2023-05-26 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zafsapp', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='TeamImage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
