# Generated by Django 4.2 on 2023-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zafsapp', '0004_gallery_alter_team_image_alter_team_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='publications')),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
