# Generated by Django 4.2 on 2023-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zafsapp', '0005_contact_publication_alter_member_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
