# Generated by Django 4.2 on 2023-07-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zafsapp', '0007_donation_email_donation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='contact_address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='middel_name',
            new_name='residential_address',
        ),
    ]
