# Generated by Django 4.2 on 2023-07-25 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zafsapp', '0008_rename_first_name_member_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='upload_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
